CREATE DATABASE IF NOT EXISTS task2;

USE task2;

CREATE TABLE IF NOT EXISTS DEPARTAMENT 
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);

INSERT INTO DEPARTAMENT (NAME) VALUES ('departament1');
INSERT INTO DEPARTAMENT (NAME) VALUES ('departament2');
INSERT INTO DEPARTAMENT (NAME) VALUES ('departament3');

CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DEPARTAMENT_ID INT NOT NULL,
    CHIEF_ID INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    SALARY INT NOT NULL,
    CONSTRAINT FK_DEPARTAMENT FOREIGN KEY (DEPARTAMENT_ID) REFERENCES DEPARTAMENT(ID)
);

INSERT INTO EMPLOYEE (DEPARTAMENT_ID, CHIEF_ID, NAME, SALARY) VALUES (1, 1, 'Ilya', 25000);
INSERT INTO EMPLOYEE (DEPARTAMENT_ID, CHIEF_ID, NAME, SALARY) VALUES (2, 1, 'Ivan', 30000);
INSERT INTO EMPLOYEE (DEPARTAMENT_ID, CHIEF_ID, NAME, SALARY) VALUES (3, 1, 'Andrey', 70000);
INSERT INTO EMPLOYEE (DEPARTAMENT_ID, CHIEF_ID, NAME, SALARY) VALUES (4, 1, 'Maxim', 70000);

SELECT * FROM EMPLOYEE WHERE SALARY > 50000;